<?php

declare(strict_types=1);

namespace Momentum81\PhpRemoveUnusedCss;

use MatthiasMullie\Minify\CSS;

/**
 * Remove unused CSS from a stylesheet
 */
trait RemoveUnusedCss
{
    protected array $whitelistArray = [];
    protected array $styleSheetArray = [];
    protected array $htmlFileArray = [];
    protected array $foundHtmlFiles = [];
    protected array $foundCssFiles = [];

    protected bool $minify = false;
    protected bool $skipComment = false;

    protected ?string $appendFilename = null;

    protected string $cssFileComment = "/**\n * Created at: :time:\n * \n * This file was generated by https://github.com/momentum81/php-remove-unused-css and should not be edited - please re-run the refactor process again instead\n */\n";

    /**
     * Specify if we should minify or not
     */
    public function minify(bool $bool = true): static
    {
        $this->minify = $bool;

        return $this;
    }

    /**
     * Specify if we should skip adding the comment to the file or not
     */
    public function skipComment(bool $bool = true): static
    {
        $this->skipComment = $bool;

        return $this;
    }

    /**
     * Overwrite the CSS comment
     */
    public function comment(string $string): static
    {
        $this->cssFileComment = $string;

        return $this;
    }

    /**
     * Append the filenames of the CSS with this value (e.g. bootstrap.stripped.css)
     */
    public function setFilenameSuffix(string $string = '.refactored.min'): static
    {
        $this->appendFilename = $string;

        return $this;
    }

    /**
     * Add items to the whitelist array
     */
    public function whitelist(string ...$selectors): static
    {
        foreach ($selectors as $whitelist) {
            if (!in_array($whitelist, $this->whitelistArray, true)) {
                $this->whitelistArray[] = $whitelist;
            }
        }

        return $this;
    }

    /**
     * Add items to the style sheets array
     */
    public function styleSheets(string ...$styleSheets): static
    {
        foreach ($styleSheets as $styleSheet) {
            if (!in_array($styleSheet, $this->styleSheetArray, true)) {
                $this->styleSheetArray[] = $styleSheet;
            }
        }

        return $this;
    }

    /**
     * Add items to the html files array
     */
    public function htmlFiles(string ...$htmlFiles): static
    {
        foreach ($htmlFiles as $htmlFile) {
            if (!in_array($htmlFile, $this->htmlFileArray, true)) {
                $this->htmlFileArray[] = $htmlFile;
            }
        }

        return $this;
    }

    /**
     * Get the comment (if required) for the top of the CSS
     */
    protected function getComment(): string
    {
        if ($this->skipComment) {
            return '';
        }

        return str_replace(':time:', date('jS M Y, g:ia'), $this->cssFileComment);
    }

    /**
     * Find all relevant HTML based files we want to scan for used CSS elements
     */
    protected function findAllHtmlFiles(): void
    {
        foreach ($this->htmlFileArray as $searchPattern) {
            $files = glob($searchPattern);
            if ($files !== false) {
                $this->foundHtmlFiles = array_merge($this->foundHtmlFiles, $files);
            }
        }
    }

    /**
     * Find all relevant CSS files to scan
     */
    protected function findAllStyleSheetFiles(): void
    {
        foreach ($this->styleSheetArray as $searchPattern) {
            $files = glob($searchPattern);
            if ($files !== false) {
                $this->foundCssFiles = array_merge($this->foundCssFiles, $files);
            }
        }

        if ($this->appendFilename !== null && $this->appendFilename !== '') {
            $this->foundCssFiles = array_filter(
                $this->foundCssFiles, 
                fn(string $filename) => !str_contains($filename, $this->appendFilename)
            );
        }
    }

    /**
     * Create and fill a new file
     */
    protected function createFile(string $filename, string $source): void
    {
        touch($filename);
        file_put_contents($filename, $source);
    }

    /**
     * Minify some CSS
     */
    protected function performMinification(string $string): string
    {
        $minifier = new CSS();
        $minifier->add($string);

        return $this->getComment() . $minifier->minify();
    }
}
